### ISSUE TITLE
Strange modified date in 0.1.3 artifact

### ISSUE THREAD

**Issue by tbinna** [sangria-graphql/macro-visit#134]
I am using org.sangria-graphql:sangria_2.13:3.0.0 dependency in a Maven project which uses org.apache.maven.plugins:maven-dependency-plugin:3.2.0:unpack-dependencies during the package phase. Unfortunately, the package phase keeps failing with the following error when the maven-dependency-plugin tries to expand the macro-visit_2.13-0.1.3.jar (which is a transitive dependency of org.sangria-graphql:sangria_2.13:3.0.0) into the target/classes directory:

```
org.apache.maven.plugin.PluginExecutionException: Execution null of goal org.apache.maven.plugins:maven-dependency-plugin:3.2.0:unpack-dependencies failed: Negative time
```

To investigate, I downloaded the macro-visit_2.13-0.1.3.jar from https://mvnrepository.com/artifact/org.sangria-graphql/macro-visit_2.13/0.1.3 and unzipped it on my local machine and found some strange modified dates which are likely the root cause for this issue.

![image](https://user-images.githubusercontent.com/1586709/168745491-f24145f3-d577-4b2b-bf08-f85275938b20.png)

Not quite sure how that happened. Maybe a glitch during the build? Other sangria dependencies seem to be just fine. Maybe a simple rebuild and release will fix the issue.

For now, I have manually added a dependency on macro-visit_2.13:0.1.2 which does not expose this problem and gets my build to pass.

**Comment by yanns** [comment]
very strange. Do you have the same issue with newer versions?
